version: 0.2
        
phases:
  install:
    commands:
      - touch build.log
      - ls -flash
  build:
    commands:
      - sed -i "s/version/$CODEBUILD_BUILD_ID/g" index.html
      - cat index.html

artifacts:
  files:
    - index.html