version: 0.2
        
phases:
  install:
    commands:
      - touch build.log
  build:
    commands:
      - sed -i 's/\$version/$CODEBUILD_BUILD_ID/' index.html

artifacts:
  files:
    - index.html